spring.application.name=dynamia-reports
spring.datasource.driver-class-name=${REPORTS_DB_DRIVER:org.hsqldb.jdbc.JDBCDriver}
spring.datasource.url=${REPORTS_DB_URL:jdbc:hsqldb:file:${REPORTS_HOME:.}/reports.db}
spring.datasource.username=${REPORTS_DB_USER:}
spring.datasource.password=${REPORTS_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${REPORTS_DB_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${REPORTS_DB_SHOW_SQL:true}

dynamia.app.name=DynamiaReports v${project.version}
dynamia.app.base-package=tools.dynamia
dynamia.app.template=Dynamical
dynamia.app.default-icon=/static/icon.png
dynamia.app.default-logo=/static/logo.png
logging.file.name=${REPORTS_HOME:.}/reports.log

server.servlet.session.tracking-modes=cookie
