version: "3.9"

services:
  reports:
    image: docker.dynamia.tools/reports:latest
    container_name: dynamia-reports
    restart: unless-stopped
    environment:
      - REPORTS_HOME=/app/reports
    volumes:
      - ./data/reports:/app/reports
    ports:
      - "8080:8080" # Ajusta si tu app expone en otro puerto
    networks:
      - dynamia-net

networks:
  dynamia-net:
    driver: bridge

