version: "3.9"

services:
  reports:
    image: docker.dynamia.tools/reports:latest
    container_name: dynamia-reports
    restart: unless-stopped
    environment:
      - REPORTS_HOME=/app/reports
      - SERVER_PORT=8081
      - SPRING_SERVER_SERVLET_SESSION_TIMEOUT=30m
    volumes:
      - reports-data:/app/reports
    ports:
      - "8081:8081"
    networks:
      - dynamia-net

networks:
  dynamia-net:
    driver: bridge

volumes:
  reports-data:
